name: Rebase
on:
  push:
    branches: [master]
jobs:
  rebase:
    runs-on: ubuntu-latest
    steps:
      - uses: peter-evans/rebase@v2
        with:
          token: ${{ secrets.CR_PAT }}
          base: master
